export default function VegetablesContent() {
    var VegetablesContent = {
        "January": {
            "totalNumbers": "4",
            "1": {
                "name": "Cabbage",
                "description": "Cabbage or headed cabbage is a leafy green, red (purple), or white (pale green) biennial plant grown as an annual vegetable crop for its dense-leaved heads.",
                "nutrition": "• It is very low in Saturated Fat and Cholesterol. It is also a good source of Thiamin, Calcium, Iron, Magnesium, Phosphorus and Potassium, and a very good source of Dietary Fiber, Vitamin C, Vitamin K, Vitamin B6, Folate and Manganese.",
                "benefits": "• Cabbage is a low-calorie vegetable that is rich in vitamins, minerals and antioxidants.<br/>• Cabbage is a good source of soluble fiber and plant sterols. These substances help in reducing cholesterol.<br/>• Potassium helps keep blood pressure within a healthy range. Increasing your intake of potassium-rich foods like cabbage help lower blood pressure levels.",
                "media": "1BYu0tOEv6EeqpEnL4-zRXhERijuNkxJ6",
            },
            "2": {
                "name": "Leek",
                "description": "The leek is a vegetable belonging to the genus Allium, which includes onions, garlic, shallots, scallions, chives, and Chinese onions.",
                "nutrition": "• The food is low in Sodium, and very low in Saturated Fat and Cholesterol. It is also a good source of Dietary Fiber, Vitamin B6, Iron and Magnesium, and a very good source of Vitamin A, Vitamin C, Vitamin K, Folate and Manganese.",
                "benefits": " Anaemia is a health condition when your blood does not make enough red blood cells or haemoglobin. Leeks help supply the body with iron to be used in haemoglobin.<br/>• Leeks have a good amount of folate. Folate consumption during pregnancy is key to preventing congenital disabilities like neural tube defects.<br/>• Leeks contain calcium, magnesium, copper, manganese, and other microelements in their bioavailable form. The calcium along with magnesium is essential for bone health, helping to convert vitamin D into its active form in the body and thus strengthen the bones.",
                "media": "1gwTxRaJ1mioctW4M50vvd8J3FNvh9rUG",
            },
            "3": {
                "name": "Broccoli",
                "description": "Broccoli is an edible green plant in the cabbage family whose large flowering head is eaten as a vegetable.",
                "nutrition": "• It is low in Saturated Fat, and very low in Cholesterol. It is also a good source of Protein, Thiamin, Pantothenic Acid, Calcium, Iron, Magnesium and Phosphorus, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Vitamin E (Alpha Tocopherol), Vitamin K, Riboflavin, Vitamin B6, Folate, Potassium and Manganese.",
                "benefits": "Broccoli contains several carotenoids. These are plant compounds that may improve eye health and reduce the risk of eye-related diseases.<br/>• Broccoli lower cholesterol levels by binding to bile acids in the gut, causing them to be expelled from the body. This reduces total cholesterol in the body.<br/>• Eating broccoli may support bowel regularity and healthy gut bacteria.<br/>• Sulforaphane, a compound found in broccoli helps in slowing the aging process.<br/>• Certain nutrients found in broccoli are associated with a decreased risk of certain dental and oral diseases.",
                "media": "1TOpekW8A9ExsAwg-QvPqtpLQFSLk-zne",
            },
            "4": {
                "name": "Cauliflower",
                "description": "Cauliflower is one of several vegetables in the species Brassica oleracea in the genus Brassica, which is in the family Brassicaceae. It is an annual plant that reproduces by seed. Typically, only the head is eaten.",
                "nutrition": "• The food is low in Saturated Fat, and very low in Cholesterol. It is also a good source of Protein, Thiamin, Riboflavin, Niacin, Iron, Magnesium, Phosphorus and Zinc, and a very good source of Dietary Fiber, Vitamin C, Vitamin B6, Folate, Pantothenic Acid, Potassium and Manganese.",
                "benefits": "Cauliflower contains vitamin C, which helps with collagen production, and vitamin K, which may help prevent bone loss.<br/>• Cauliflower and other cruciferous vegetables contain Indole-3-carbinol, a phytonutrient that has been shown to aid the liver in its detox functions.<br/>• Choline, a nutrient found in cauliflower and other vegetables, helps with gastrointestinal health. Also, glutathione is an antioxidant that helps fight off infection.",
                "media": "10ytJWOIVEGzmQhV9hDtGNcvC5AgnM98a",
            },
        },
        "February": {
            "totalNumbers": "4",
            "1": {
                "name": "Carrot",
                "description": "The carrot is a root vegetable, usually orange in colour, though purple, black, red, white, and yellow cultivars exist. Carrots are a domesticated form of the wild carrot, Daucus carota, native to Europe and southwestern Asia.",
                "nutrition": "• The food is very low in Saturated Fat and Cholesterol. It is also a good source of Vitamin C, Vitamin E (Alpha Tocopherol), Thiamine and Potassium, and a very good source of Dietary Fiber, Vitamin A, Vitamin K, Vitamin B6 and Manganese.",
                "benefits": "Carrots increase saliva and supply essential minerals, vitamins and enzymes that aid in digestion. Eating carrots regularly may help prevent gastric ulcers and other digestive disorders.<br/>• Carrots kill harmful germs in the mouth and help prevent tooth decay.<br/>• Raw or grated carrots can be used to help heal wounds, cuts and inflammation.<br/>• The nutrients in carrots can improve the health of your eyes, skin, hair, nails and more through helping to detoxify your system and build new cells!",
                "media": "1ftXLRxlznMvYU61M7jKXaQSCfMdgWXKR",
            },
            "2": {
                "name": "Pumpkin",
                "description": "The leek is a vegetable belonging to the genus Allium, which includes onions, garlic, shallots, scallions, chives, and Chinese onions.",
                "nutrition": "• It is also a good source of Vitamin E (Alpha Tocopherol), Thiamin, Niacin, Vitamin B6, Folate, Iron, Magnesium and Phosphorus, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Riboflavin, Potassium, Copper and Manganese.",
                "benefits": "Pumpkin contains beta-carotene. Your body can turn beta-carotene into Vitamin A, which strengthens your immune system.<br/>• Vitamin A, paired with the Lutein and Zeaxanthin found in pumpkin, makes the squash a food that decreases risk of sight loss.<br/>• Pumpkin is full of nutrients like fibre, vitamin C, and potassium which lower blood pressure. Additionally, the antioxidants in pumpkin work against the oxidation of bad cholesterol.<br/>• Pumpkin’s health benefits extend even to your skin.  Beta-carotene works as a natural sunscreen for your skin, protecting it from harmful UV rays, and preventing skin cancer from developing.",
                "media": "1wx3rsUMPyr2niUuzkwv5AAxqZT_hTALI",
            },
            "3": {
                "name": "Brussels Sprouts",
                "description": "The Brussels sprout is a member of the Gemmifera Group of cabbages, grown for its edible buds.",
                "nutrition": "It is also a good source of Thiamin, Riboflavin, Iron, Magnesium, Phosphorus and Copper, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Vitamin K, Vitamin B6, Folate, Potassium and Manganese.",
                "benefits": "Brussels sprouts contain kaempferol, an antioxidant that may reduce cancer growth, decrease inflammation and promote heart health.<br/>• Brussels sprouts are high in fiber, which can promote regularity, support digestive health and reduce the risk of heart disease and diabetes.<br/>• Brussels sprouts are a good source of ALA omega-3 fatty acids, which can reduce inflammation, insulin resistance, cognitive decline and blood triglycerides.",
                "media": "1gULwE9dG68MQGhKRxyKR1d_OGdEWeiWQ",
            },
            "4": {
                "name": "Turnip",
                "description": "The turnip or white turnip is a root vegetable commonly grown in temperate climates worldwide for its white, fleshy taproot.",
                "nutrition": "This food is very low in Saturated Fat and Cholesterol. It is also a good source of Vitamin B6, Calcium, Phosphorus and Manganese, and a very good source of Dietary Fiber, Vitamin C and Potassium.",
                "benefits": "Turnips have a number of essential nutrients that our body needs for proper functioning, including high levels of potassium and fiber.<br/>• Turnips have a number of essential nutrients that our body needs for proper functioning, including high levels of potassium and fiber.<br/>• The turnip greens are packed with beneficial omega-3 fatty acids and vitamin K, which are important if you suffer from any inflammatory conditions.",
                "media": "18zu2x-hEp1jv8uI9qmWXyz0AgJlnboYH",
            },
        },
        "March": {
            "totalNumbers": "3",
            "1": {
                "name": "Lettuce",
                "description": "Lettuce is most often grown as a leaf vegetable, but sometimes for its stem and seeds. Lettuce is most often used for salads, although it is also seen in other kinds of food, such as soups, sandwiches and wraps; it can also be grilled.",
                "nutrition": "It is also a good source of Protein, Calcium, Magnesium and Phosphorus, and a very good source of Dietary Fiber, Thiamin, Riboflavin, Folate, Iron, Potassium and Manganese.<br/>• Vitamins in lettuce are plentiful. Its fresh leaves are an excellent source of several Vitamin-A and β-carotenes.",
                "benefits": "Lettuce possesses anti-inflammatory properties that help in controlling inflammation. Lettuce extracts have shown significant controlling power over inflammation induced by biocatalysts like lipoxygenase and carrageenan.<br/>• Lettuce can be beneficial in lowering high cholesterol levels that often lead to cardiovascular diseases and other dangerous conditions.<br/>• One of the major traditional uses of lettuce in Unani medicine was as a sleep inducer.<br/>• Lettuce possesses anxiolytic properties.<br/>• Regular inclusion of lettuce in salads is known to prevent osteoporosis, iron-deficiency anaemia.",
                "media": "15PRys-rVxjLWC_L8Rv4ufU-Hu-vcwV_z",
            },
            "2": {
                "name": "Artichoke",
                "description": "The globe artichoke is a variety of a species of thistle cultivated as a food. The edible portion of the plant consists of the flower buds before the flowers come into bloom.",
                "nutrition": "They are low in saturated fat and cholesterol while being a rich source of fiber, vitamins, and minerals.<br/>• They contain vitamins which include vitamin C, thiamin, riboflavin, niacin, folate, vitamin B-6, B-12, A, E, D, and vitamin K.<br/>• They also provide minerals such as calcium, iron, zinc, sodium, potassium, manganese, phosphorus, and zinc.",
                "benefits": "Certain ingredients in their leaves have been found to reduce the levels of bad cholesterol (LDL) and increase the levels of good cholesterol (HDL or omega-3 fatty acids).<br/>• Two antioxidants found in artichokes, cynarin and silymarin, have been shown to improve the overall health of the liver by reducing the presence of toxins and facilitating their elimination from the liver and the body.<br/>• Artichokes make a perfect hangover cure. Some people choose to chew on a few artichoke leaves after a night of heavy drinking.<br/>• Artichokes even help pregnant women have healthy, normally-formed children. The high levels of folic acid found in artichokes can prevent neural tube defects from occurring in newborns.",
                "media": null,
            },
            "3": {
                "name": "Broccoli",
                "description": "Broccoli is an edible green plant in the cabbage family whose large flowering head is eaten as a vegetable.",
                "nutrition": "It is low in Saturated Fat, and very low in Cholesterol. It is also a good source of Protein, Thiamin, Pantothenic Acid, Calcium, Iron, Magnesium and Phosphorus, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Vitamin E (Alpha Tocopherol), Vitamin K, Riboflavin, Vitamin B6, Folate, Potassium and Manganese.",
                "benefits": "Broccoli contains several carotenoids. These are plant compounds that may improve eye health and reduce the risk of eye-related diseases.<br/>• Broccoli lower cholesterol levels by binding to bile acids in the gut, causing them to be expelled from the body. This reduces total cholesterol in the body.<br/>• Eating broccoli may support bowel regularity and healthy gut bacteria.<br/>• Sulforaphane, a compound found in broccoli helps in slowing the aging process.<br/>• Certain nutrients found in broccoli are associated with a decreased risk of certain dental and oral diseases.",
                "media": "1TOpekW8A9ExsAwg-QvPqtpLQFSLk-zne",
            },
        },
        "April": {
            "totalNumbers": "4",
            "1": {
                "name": "Asparagus",
                "description": "Asparagus, or garden asparagus, is a perennial flowering plant species in the genus Asparagus. Its young shoots are used as a spring vegetable.",
                "nutrition": "Asparagus is a very low-calorie vegetable.<br/>• Its shoots are rich in the B-complex group of vitamins such as thiamine, riboflavin, niacin, vitamin B-6 (pyridoxine), and pantothenic acid.<br/>• Asparagus is an excellent source of minerals, especially copper and iron.",
                "benefits": "Asparagus is a good source of antioxidants, including vitamins C and E, flavonoids and polyphenols.<br/>• Asparagus has a number of features that make it a weight-loss friendly food.<br/>• Asparagus contains potassium, a mineral that can help lower high blood pressure.",
                "media": "13NFhflOVdXtL2k1cuyCqsBjOPiDe-74G",
            },
            "2": {
                "name": "Green Peas",
                "description": "The pea is most commonly the small spherical seed or the seed-pod of the pod fruit Pisum sativum. Each pod contains several peas, which can be green or yellow",
                "nutrition": "Peas are one of the most nutritious leguminous vegetables rich in health promoting phytonutrients, minerals, vitamins and antioxidants.<br/>• Peas contain phytosterols, especially ß-sitosterol.<br/>• Peas are healthy sources of ascorbic acid (vitamin-C), vitamin-K, vitamin-A.<br/>• They are a rich source of many minerals such as calcium, iron, copper, zinc, and manganese.",
                "benefits": "Peas are low fat but high everything else.<br/>• They have many antioxidant and anti-inflammatory compounds that support healthy blood vessels.<br/>• The high fibre content in peas improves bowel health and peristalsis.<br/>• The niacin in peas helps reduce, the production of triglycerides and VLDL (very low-density lipoprotein), which results in in less bad cholesterol.",
                "media": "1W9wzl-V7KpwjT9vTPBgL2tPhrhBQN__i",
            },
            "3": {
                "name": "Zucchini (turee)",
                "description": "The zucchini is a summer squash which can reach nearly 1 metre in length, but is usually harvested when still immature at about 15 to 25 cm.",
                "nutrition": "Zucchini is rich in flavonoid polyphenolic antioxidants such as carotenes, lutein, and zeaxanthin.<br/> • It is an excellent source of potassium, an important intracellular electrolyte.<br/>• They contain moderate levels of the B-complex group of vitamins like thiamine, pyridoxine, riboflavin and minerals like iron, manganese, phosphorus, and zinc.",
                "benefits": "Zucchini is rich in flavonoid polyphenolic antioxidants such as carotenes, lutein, and zeaxanthin.<br/> • It is an excellent source of potassium, an important intracellular electrolyte.<br/>• They contain moderate levels of the B-complex group of vitamins like thiamine, pyridoxine, riboflavin and minerals like iron, manganese, phosphorus, and zinc.",
                "media": "1iOQ_HzZVVRJRsElHZGXmzWsb9Y4yzK8m",
            },
            "4": {
                "name": "Spring Onion",
                "description": "Scallions are vegetables of various Allium onion species. Scallions have a milder taste than most onions. Their close relatives include garlic, shallot, leek, chive, and Chinese onion.",
                "nutrition": "This food is low in Sodium, and very low in Saturated Fat and Cholesterol. It is also a good source of Thiamin, Riboflavin, Magnesium, Phosphorus and Copper, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Vitamin K, Folate, Calcium, Iron, Potassium and Manganese.",
                "benefits": "Spring onions are always preferred as appetizers. They are rich in fiber and helps in better digestion.<br/>• Spring onions have carotenoids which helps to keep the vision healthy and intact. It is also rich in vitamin A which prevents loss of eyesight.<br/>• Due to its antibacterial and antiviral properties, it is an excellent medicine to fight against viral and flu. It also helps in reducing excess mucus and fights against the winter cold which often ends up making you feel miserable.",
                "media": "1G34Mk3dvuSU0ssY8DJGppIfe4sHgz9UI",
            },
        },
        "May": {
            "totalNumbers": "3",
            "1": {
                "name": "Green Beans",
                "description": "Green beans are the unripe, young fruit and protective pods of various cultivars of the common bean.",
                "nutrition": "This food is low in Saturated Fat, and very low in Cholesterol. It is also a good source of Thiamin, Riboflavin, Calcium, Iron, Magnesium and Potassium, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Vitamin K, Folate and Manganese",
                "benefits": "This nutritional powerhouse can do wonders for your skin, hair and nails. Green beans are loaded with an easily absorbed type of silicon, which are important for the formation of healthy connective tissues and strengthening nails and boosting skin health.<br/>• Green beans are loaded with antioxidants preventing the free radical damage activity.<br/>• Rich in carotenoids, green beans could play an effective role in preventing macular degeneration. They are also rich in lutein and Zeaxanthin which help maintain good eyesight and night vision.<br/>• Green beans with its strong diuretic properties can serve as a great detox and help rid your body from unwanted toxins.",
                "media": "1ygxX4dGjDR4OQTI1WLygG0PYecObvRoY",
            },
            "2": {
                "name": "Lettuce",
                "description": "Lettuce is most often grown as a leaf vegetable, but sometimes for its stem and seeds. Lettuce is most often used for salads, although it is also seen in other kinds of food, such as soups, sandwiches and wraps; it can also be grilled.",
                "nutrition": "It is also a good source of Protein, Calcium, Magnesium and Phosphorus, and a very good source of Dietary Fiber, Thiamin, Riboflavin, Folate, Iron, Potassium and Manganese.<br/>• Vitamins in lettuce are plentiful. Its fresh leaves are an excellent source of several Vitamin-A and β-carotenes.",
                "benefits": "Lettuce possesses anti-inflammatory properties that help in controlling inflammation. Lettuce extracts have shown significant controlling power over inflammation induced by biocatalysts like lipoxygenase and carrageenan.<br/>• Lettuce can be beneficial in lowering high cholesterol levels that often lead to cardiovascular diseases and other dangerous conditions.<br/>• One of the major traditional uses of lettuce in Unani medicine was as a sleep inducer.<br/>• Lettuce possesses anxiolytic properties.<br/>• Regular inclusion of lettuce in salads is known to prevent osteoporosis, iron-deficiency anaemia.",
                "media": "15PRys-rVxjLWC_L8Rv4ufU-Hu-vcwV_z",
            },
            "3": {
                "name": "Corn Salad",
                "description": "It has a characteristic nutty flavour, dark green colour, and soft texture, and is popularly served as salad greens.",
                "nutrition": "This food is very low in Saturated Fat and Cholesterol. It is also a good source of Vitamin C, Vitamin B6, Folate, Potassium and Copper, and a very good source of Dietary Fiber, Vitamin A and Vitamin K.<br/>• Corn contains higher amounts of antioxidants than many other cereal grains.",
                "benefits": "Corn does not promote diverticular disease. On the contrary, it seems to be protective.<br/>• Corn is fairly high in fiber. Infact, one bag of corn contain a large proportion of the recommended daily intake.<br/>• Being a good source of lutein and zeaxanthin, corn contribute in the maintenance of eye health.",
                "media": "1NaZgVdXNRmxgC-pepGVkBIztjodox4RV",
            },
        },
        "June": {
            "totalNumbers": "4",
            "1": {
                "name": "Cucumber",
                "description": "Cucumber is a widely cultivated plant in the gourd family, Cucurbitaceae. It is a creeping vine that bears cucumiform fruits that are used as vegetables.",
                "nutrition": "Cucumbers are low in calories but high in several important vitamins and minerals.<br/>• Cucumbers contain good amount of fiber and water.",
                "benefits": "Cucumbers contain antioxidants, including flavonoids and tannins, which prevent the accumulation of harmful free radicals and reduce the risk of chronic disease.<br/>• Cucumbers are composed of about 96% water, which increase hydration and help meet the daily fluid needs.<br/>• Cucumbers can be eaten fresh or pickled. They can be enjoyed as a low-calorie snack or used to add flavor in variety of dishes.",
                "media": "1FMHM-US42q_AWZXUbnGhYhUGuUZ-NJ_p",
            },
            "2": {
                "name": "Tomatoes",
                "description": "The tomato is the edible, often red, berry of the nightshade Solanum lycopersicum, commonly known as a tomato plant.",
                "nutrition": "Fresh tomatoes are low in carbs. The carb content consists mainly of simple sugars and insoluble fibers.<br/>• Tomatoes are good source of several vitamins and minerals, such as vitamin C, potassium, vitamin K and folate.<br/>• The main plant compound in tomatoes is lycopene. They also contain beta-carotene, naringenin and chlorogenic acid.",
                "benefits": "Tomatoes and tomato products reduce the risk of heart disease and several cancers. They are also considered to be beneficial for skin health, and may protect against sunburns.<br/>• The fluid and fiber in tomatoes may be helpful if you're prone to constipation.<br/>• Lycopene is  good for eyes. They support vision and protect against eye conditions including cataracts and macular degeneration.",
                "media": "1Hqkk5gIhUEuPARVOUiTISiq9eAFlSTh8",
            },
            "3": {
                "name": "Potatoes",
                "description": "The potato is a starchy, tuberous crop from the perennial nightshade Solanum tuberosum.",
                "nutrition": "Potatoes are packed with vitamins and minerals, through the variety and preparation method can affect the nutritional content. ",
                "benefits": "Potatoes are a good source of antioxidants, which reduce the risk of chronic diseases like heart disease, diabetes and certain cancers.<br/>• Potatoes contain resistant starch, which helps reduce insulin resistance. In turn, this can help improve blood sugar control.<br/>• Resistant starch in potatoes is a source of the nutrition for beneficial gut bacteria. They convert it to the short-chain fatty acid butyrate, which reduce inflammation in the colon, improved colon defenses and a lower risk of colorectal cancer.<br/>• Potatoes are among the most filling foods. They increase the levels of fullness hormones, such as cholecystokinin (CCK).",
                "media": "10Wp9E7Dn42D-FrFbgNeTlyPsQt9DqZD3",
            },
            "4": {
                "name": "Chard (Chauli Saag)",
                "description": "Chard is a green leafy vegetable. The leaf blade can be green or reddish in color; the leaf stalks are usually white, yellow, or red.",
                "nutrition": "Chard is a low-calorie vegetable that is high in magnesium, iron, potassium and vitamins A,C and K.<br/>• Chard is high in fiber.<br/>• Chard is an excellent source of vitamin K.",
                "benefits": "Chard is high in many antioxidants including beta-carotene and flavonoids, which help prevent certain conditions like heart disease and lung cancer.<br/> • Chard is high in fiber and antioxidants, which improve blood sugar control and lower risk of diabetes.<br/>• Chard is weight loss friendly food.",
                "media": "13bV097DXldBVua5Fw4h16DZUKks4Aftb",
            },
        },
        "July": {
            "totalNumbers": "4",
            "1": {
                "name": "Spinach (Palak)",
                "description": "Spinach is an edible flowering plant in the family Amaranthaceae native to central and western Asia. Its leaves are commonly eaten as a vegetable, either fresh, frozen, canned, chopped, or dehydrated. It is an annual plant growing as tall as 30 cm.",
                "nutrition": "It is also a good source of Niacin, and a very good source of Dietary Fiber, Protein, Vitamin A, Vitamin C, Vitamin E (Alpha Tocopherol), Vitamin K, Thiamin, Riboflavin, Vitamin B6, Folate, Calcium, Iron,, Phosphorus, Potassium, Zinc, Copper.<br/>• Spinach is also one of the best sources of dietary magnesium.",
                "benefits": "Spinach contains an antioxidant known as alpha-lipoic acid, which has been shown to lower glucose levels, increase insulin sensitivity, and prevent oxidative, stress-induced changes in patients with diabetes.<br/>• Due to its high potassium content, spinach is recommended for people with high blood pressure.<br/>• Spinach is high in fiber and water, both of which help to prevent constipation and promote a healthy digestive tract.",
                "media": "18_hjFdX71jKsplSfo_8EosghaYAO1hKC",
            },
            "2": {
                "name": "Okra",
                "description": "Okra or okro, known in many English-speaking countries as ladies' fingers, is a flowering plant in the mallow family. It is valued for its edible green seed pods.",
                "nutrition": "Okra is a high-fiber food – half of its nutrition consists of soluble fiber in the form of pectins and gums.<br/> • It also contains over 10% of the RDA of folic acid.",
                "benefits": "Okra contains myricetin, a substance that increase sugar absorption by the body’s muscles. When this happens effectively, there are low sugar levels in the blood.<br/> • The fiber in okra help lower bad cholesterol levels – and this invariably contributes to heart health. It also cut the risk of cardiovascular disease and stroke.<br/> • Okra contains lectin, a type of protein. This protein help fight human breast cancer cells.",
                "media": "16M_LJWZ8oEVOivPsBqblFuFWY0tR3Phs",
            },
            "3": {
                "name": "Green Beans",
                "description": "Green beans are the unripe, young fruit and protective pods of various cultivars of the common bean.",
                "nutrition": "This food is low in Saturated Fat, and very low in Cholesterol. It is also a good source of Thiamin, Riboflavin, Calcium, Iron, Magnesium and Potassium, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Vitamin K, Folate and Manganese",
                "benefits": "This nutritional powerhouse can do wonders for your skin, hair and nails. Green beans are loaded with an easily absorbed type of silicon, which are important for the formation of healthy connective tissues and strengthening nails and boosting skin health.<br/>• Green beans are loaded with antioxidants preventing the free radical damage activity.<br/>• Rich in carotenoids, green beans could play an effective role in preventing macular degeneration. They are also rich in lutein and Zeaxanthin which help maintain good eyesight and night vision.<br/>• Green beans with its strong diuretic properties can serve as a great detox and help rid your body from unwanted toxins.",
                "media": "1ygxX4dGjDR4OQTI1WLygG0PYecObvRoY",
            },
            "4": {
                "name": "Bell Peppers (Capsicum)",
                "description": "Bell Peppers or Capsicum , the pepper, is a genus of flowering plants in the nightshade family Solanaceae.Cultivars of the plant produce fruits in different colours, including red, yellow, orange, green, white, and purple.",
                "nutrition": "Bell peppers are mainly made up of water and carbs. Most of the carbs are sugars, such as glucose and fructose. Bell peppers are also a decent source of fiber.<br/> • Bell peppers are very high in vitamin C. Other vitamins and minerals found in bell peppers include vitamin K1, vitamin E, vitamin A, folate and potassium.<br/> • Bell peppers contain many healthy antioxidants, including capsanthin, violaxanthin, lutein, quercetin and luteolin.",
                "benefits": "The phytochemical constituents of capsicum are shown to produce an anti-inflammatory response that alleviates peripheral neurogenic pain related to Crohn’s disease, an inflammatory disease of the bowels.<br/> • Capsicum contains tannins. Tannins are astringent and are often considered for their benefits when treating gastrointestinal disorders such as diarrhea, dysentery, and other microbial disorders.<br/> • Many clinical trials show the effectiveness of capsicum for treating symptoms of fibromyalgia when applied topically. Those using capsicum topically stated beneficial effects in the improvement of sleep.",
                "media": "1TgiVU6GuuNoQgQsDGds5v0_QDJ7kyrj4",
            },
        },
        "August": {
            "totalNumbers": "4",
            "1": {
                "name": "Radish",
                "description": "The radish is an edible root vegetable of the Brassicaceae family. Radishes are grown and consumed throughout the world, being mostly eaten raw as a crunchy salad vegetable",
                "nutrition": "They contain many phytochemicals like indoles and zeaxanthin, lutein, and beta-carotene, which are flavonoid antioxidants.<br/>• Fresh roots are a good source of vitamin-C.<br/>• They contain adequate levels of folates, vitamin B-6, riboflavin, thiamin and minerals such as iron, magnesium, copper and calcium.",
                "benefits": "Radish is known to control damage to our red blood cells, and in the process also increases oxygen supply to the blood.<br/>• Radishes are a good source for anthocyanins that keep our hearts functioning properly, reducing the risk of cardiovascular diseases.<br/>• This root vegetable is not only good for your digestive system, but it also helps to fix acidity, obesity, gastric problems, and nausea, among others.<br/>•Radish plays an important role in the generation of collagen, which in turn boosts our blood vessels and decreases our chances of getting atherosclerosis.",
                "media": "1WStvreVwMOZJmdWH9V7Mc4AmmzXuWZMh",
            },
            "2": {
                "name": "Cauliflower",
                "description": "Cauliflower is one of several vegetables in the species Brassica oleracea in the genus Brassica, which is in the family Brassicaceae. It is an annual plant that reproduces by seed. Typically, only the head is eaten.",
                "nutrition": "The food is low in Saturated Fat, and very low in Cholesterol. It is also a good source of Protein, Thiamin, Riboflavin, Niacin, Iron, Magnesium, Phosphorus and Zinc, and a very good source of Dietary Fiber, Vitamin C, Vitamin B6, Folate, Pantothenic Acid, Potassium and Manganese.",
                "benefits": "Cauliflower contains vitamin C, which helps with collagen production, and vitamin K, which may help prevent bone loss.<br/> • Cauliflower and other cruciferous vegetables contain Indole-3-carbinol, a phytonutrient that has been shown to aid the liver in its detox functions.<br/> • Eating cauliflower can help boost HDL cholesterol (the good kind) levels and lower blood pressure.<br/> • Choline, a nutrient found in cauliflower and other vegetables, helps with gastrointestinal health. Also, glutathione is an antioxidant that helps fight off infection.",
                "media": "10ytJWOIVEGzmQhV9hDtGNcvC5AgnM98a",
            },
            "3": {
                "name": "Tomatoes",
                "description": "The tomato is the edible, often red, berry of the nightshade Solanum lycopersicum, commonly known as a tomato plant.",
                "nutrition": "Fresh tomatoes are low in carbs. The carb content consists mainly of simple sugars and insoluble fibers.<br/> • Tomatoes are good source of several vitamins and minerals, such as vitamin C, potassium, vitamin K and folate.<br/> • The main plant compound in tomatoes is lycopene. They also contain beta-carotene, naringenin and chlorogenic acid.",
                "benefits": "Tomatoes and tomato products reduce the risk of heart disease and several cancers. They are also considered to be beneficial for skin health, and may protect against sunburns.<br/> • The fluid and fiber in tomatoes may be helpful if you're prone to constipation.<br/> • Lycopene is  good for eyes. They support vision and protect against eye conditions including cataracts and macular degeneration.",
                "media": "1Hqkk5gIhUEuPARVOUiTISiq9eAFlSTh8",
            },
            "4": {
                "name": "Beet",
                "description": "The beetroot is the taproot portion of the beet plant. As the beet and also known as the table beet, garden beet, red beet, or golden beet. It is one of several of the cultivated varieties of Beta vulgaris grown for their edible taproots and their leaves.",
                "nutrition": "It is very low in Saturated Fat and Cholesterol. It is also a good source of Dietary Fiber, Vitamin C, Magnesium and Potassium, and a very good source of Folate and Manganese.",
                "benefits": "Beets are rich in nitrates, which the body converts to nitric oxide—a compound that relaxes and dilates blood vessels, turning them into superhighways for your nutrient- and oxygen-rich blood.<br/> • They are also rich in the B-vitamin folate.<br/> • Beets are also rich in betalains, a class of potent antioxidants and anti-inflammatories that battle free radical- and inflammation-related chronic diseases like heart disease, obesity, and possibly cancer.",
                "media": "1DIvzxoGDNk4G2etvVAttecb8Lr2wAtQ4",
            },
        },
        "September": {
            "totalNumbers": "4",
            "1": {
                "name": "Cabbage",
                "description": "Cabbage or headed cabbage is a leafy green, red (purple), or white (pale green) biennial plant grown as an annual vegetable crop for its dense-leaved heads.",
                "nutrition": "It is very low in Saturated Fat and Cholesterol. It is also a good source of Thiamin, Calcium, Iron, Magnesium, Phosphorus and Potassium, and a very good source of Dietary Fiber, Vitamin C, Vitamin K, Vitamin B6, Folate and Manganese.",
                "benefits": "• Cabbage is a low-calorie vegetable that is rich in vitamins, minerals and antioxidants.<br/>• Cabbage is a good source of soluble fiber and plant sterols. These substances help in reducing cholesterol.<br/>• Potassium helps keep blood pressure within a healthy range. Increasing your intake of potassium-rich foods like cabbage help lower blood pressure levels.",
                "media": "1BYu0tOEv6EeqpEnL4-zRXhERijuNkxJ6",
            },
            "2": {
                "name": "Carrot",
                "description": "The carrot is a root vegetable, usually orange in colour, though purple, black, red, white, and yellow cultivars exist. Carrots are a domesticated form of the wild carrot, Daucus carota, native to Europe and southwestern Asia.",
                "nutrition": "The food is very low in Saturated Fat and Cholesterol. It is also a good source of Vitamin C, Vitamin E (Alpha Tocopherol), Thiamine and Potassium, and a very good source of Dietary Fiber, Vitamin A, Vitamin K, Vitamin B6 and Manganese.",
                "benefits": "Carrots increase saliva and supply essential minerals, vitamins and enzymes that aid in digestion. Eating carrots regularly may help prevent gastric ulcers and other digestive disorders.<br/> • Carrots kill harmful germs in the mouth and help prevent tooth decay.<br/> • Raw or grated carrots can be used to help heal wounds, cuts and inflammation.<br/> • The nutrients in carrots can improve the health of your eyes, skin, hair, nails and more through helping to detoxify your system and build new cells!",
                "media": "1ftXLRxlznMvYU61M7jKXaQSCfMdgWXKR",
            },
            "3": {
                "name": "Green Peas",
                "description": "The pea is most commonly the small spherical seed or the seed-pod of the pod fruit Pisum sativum. Each pod contains several peas, which can be green or yellow.",
                "nutrition": "Peas are one of the most nutritious leguminous vegetables rich in health promoting phytonutrients, minerals, vitamins and antioxidants.<br/> • Peas contain phytosterols, especially ß-sitosterol.<br/> • Peas are healthy sources of ascorbic acid (vitamin-C), vitamin-K, vitamin-A.<br/> • They are a rich source of many minerals such as calcium, iron, copper, zinc, and manganese.",
                "benefits": "Peas are low fat but high everything else.<br/> • They have many antioxidant and anti-inflammatory compounds that support healthy blood vessels.<br/> • The high fibre content in peas improves bowel health and peristalsis.<br/> • The niacin in peas helps reduce, the production of triglycerides and VLDL (very low-density lipoprotein), which results in in less bad cholesterol.",
                "media": "1W9wzl-V7KpwjT9vTPBgL2tPhrhBQN__i",
            },
            "4": {
                "name": "Spring Onion",
                "description": "Scallions are vegetables of various Allium onion species. Scallions have a milder taste than most onions. Their close relatives include garlic, shallot, leek, chive, and Chinese onion.",
                "nutrition": "This food is low in Sodium, and very low in Saturated Fat and Cholesterol. It is also a good source of Thiamin, Riboflavin, Magnesium, Phosphorus and Copper, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Vitamin K, Folate, Calcium, Iron, Potassium and Manganese.",
                "benefits": "Spring onions are always preferred as appetizers. They are rich in fiber and helps in better digestion.<br/>• Spring onions have carotenoids which helps to keep the vision healthy and intact. It is also rich in vitamin A which prevents loss of eyesight.<br/>• Due to its antibacterial and antiviral properties, it is an excellent medicine to fight against viral and flu. It also helps in reducing excess mucus and fights against the winter cold which often ends up making you feel miserable.",
                "media": "1G34Mk3dvuSU0ssY8DJGppIfe4sHgz9UI",
            },
        },
        "October": {
            "totalNumbers": "3",
            "1": {
                "name": "Bell Peppers (Capsicum)",
                "description": "Capsicum , the pepper, is a genus of flowering plants in the nightshade family Solanaceae.Cultivars of the plant produce fruits in different colours, including red, yellow, orange, green, white, and purple.",
                "nutrition": "Bell peppers are mainly made up of water and carbs. Most of the carbs are sugars, such as glucose and fructose. Bell peppers are also a decent source of fiber.<br/> • Bell peppers are very high in vitamin C. Other vitamins and minerals found in bell peppers include vitamin K1, vitamin E, vitamin A, folate and potassium.<br/> • Bell peppers contain many healthy antioxidants, including capsanthin, violaxanthin, lutein, quercetin and luteolin.",
                "benefits": "The phytochemical constituents of capsicum are shown to produce an anti-inflammatory response that alleviates peripheral neurogenic pain related to Crohn’s disease, an inflammatory disease of the bowels.<br/> • Capsicum contains tannins. Tannins are astringent and are often considered for their benefits when treating gastrointestinal disorders such as diarrhea, dysentery, and other microbial disorders.<br/> • Many clinical trials show the effectiveness of capsicum for treating symptoms of fibromyalgia when applied topically. Those using capsicum topically stated beneficial effects in the improvement of sleep.",
                "media": "1TgiVU6GuuNoQgQsDGds5v0_QDJ7kyrj4",
            },
            "2": {
                "name": "Aubergine (Brinjal)",
                "description": "Eggplant, aubergine, or brinjal is a plant species in the nightshade family Solanaceae, Solanum melongena, grown for its often purple edible fruit.",
                "nutrition": "This food is very low in Saturated Fat and Cholesterol. It is also a good source of Vitamin K, Thiamin, Vitamin B6, Folate, Potassium and Manganese, and a very good source of Dietary Fiber.<br/>• Eggplants contain flavonoids, such as anthocyanins. Anthocyanins are water-soluble pigments. They also help give the eggplant its well-known, dark purple color.<br/>• The skin of the eggplant is rich in antioxidants, fiber, potassium, and magnesium.",
                "benefits": "The fiber, potassium, vitamin C, vitamin B6, and phytonutrient content in eggplants all support heart health.<br/>• Polyphenols in eggplant have anti-cancer effects.Anthocyanins and chlorogenic acid protect cells from damage caused by free radicals and, in turn, prevent tumor growth and the invasion and spread of cancer cells.<br/>• The antioxidants in eggplant may help protect the liver from certain toxins.",
                "media": "1EMqq6Okyiv3dj6EYuqhkvCXqrrSYmit-",
            },
            "3": {
                "name": "Lettuce",
                "description": "Lettuce is most often grown as a leaf vegetable, but sometimes for its stem and seeds. Lettuce is most often used for salads, although it is also seen in other kinds of food, such as soups, sandwiches and wraps; it can also be grilled.",
                "nutrition": "It is also a good source of Protein, Calcium, Magnesium and Phosphorus, and a very good source of Dietary Fiber, Thiamin, Riboflavin, Folate, Iron, Potassium and Manganese.<br/>• Vitamins in lettuce are plentiful. Its fresh leaves are an excellent source of several Vitamin-A and β-carotenes.",
                "benefits": "Lettuce possesses anti-inflammatory properties that help in controlling inflammation. Lettuce extracts have shown significant controlling power over inflammation induced by biocatalysts like lipoxygenase and carrageenan.<br/>• Lettuce can be beneficial in lowering high cholesterol levels that often lead to cardiovascular diseases and other dangerous conditions.<br/>• One of the major traditional uses of lettuce in Unani medicine was as a sleep inducer.<br/>• Lettuce possesses anxiolytic properties.<br/>• Regular inclusion of lettuce in salads is known to prevent osteoporosis, iron-deficiency anaemia.",
                "media": "15PRys-rVxjLWC_L8Rv4ufU-Hu-vcwV_z",
            },
        },
        "November": {
            "totalNumbers": "4",
            "1": {
                "name": "Turnip",
                "description": "The turnip or white turnip is a root vegetable commonly grown in temperate climates worldwide for its white, fleshy taproot.",
                "nutrition": "This food is very low in Saturated Fat and Cholesterol. It is also a good source of Vitamin B6, Calcium, Phosphorus and Manganese, and a very good source of Dietary Fiber, Vitamin C and Potassium.",
                "benefits": "Turnips have a number of essential nutrients that our body needs for proper functioning, including high levels of potassium and fiber.<br/>• Turnips have a number of essential nutrients that our body needs for proper functioning, including high levels of potassium and fiber.<br/>• The turnip greens are packed with beneficial omega-3 fatty acids and vitamin K, which are important if you suffer from any inflammatory conditions.",
                "media": "18zu2x-hEp1jv8uI9qmWXyz0AgJlnboYH",
            },
            "2": {
                "name": "Spinach",
                "description": "Spinach is an edible flowering plant in the family Amaranthaceae native to central and western Asia. Its leaves are commonly eaten as a vegetable, either fresh, frozen, canned, chopped, or dehydrated. It is an annual plant growing as tall as 30 cm.",
                "nutrition": "It is also a good source of Niacin, and a very good source of Dietary Fiber, Protein, Vitamin A, Vitamin C, Vitamin E (Alpha Tocopherol), Vitamin K, Thiamin, Riboflavin, Vitamin B6, Folate, Calcium, Iron,, Phosphorus, Potassium, Zinc, Copper.<br/> • Spinach is also one of the best sources of dietary magnesium.",
                "benefits": "Spinach contains an antioxidant known as alpha-lipoic acid, which has been shown to lower glucose levels, increase insulin sensitivity, and prevent oxidative, stress-induced changes in patients with diabetes.<br/> • Due to its high potassium content, spinach is recommended for people with high blood pressure.<br/> • Spinach is high in fiber and water, both of which help to prevent constipation and promote a healthy digestive tract.",
                "media": "18_hjFdX71jKsplSfo_8EosghaYAO1hKC",
            },
            "3": {
                "name": "Okra",
                "description": "Okra or okro, known in many English-speaking countries as ladies' fingers, is a flowering plant in the mallow family. It is valued for its edible green seed pods.",
                "nutrition": "Okra is a high-fiber food – half of its nutrition consists of soluble fiber in the form of pectins and gums.<br/> • It also contains over 10% of the RDA of folic acid.",
                "benefits": "Okra contains myricetin, a substance that increase sugar absorption by the body’s muscles. When this happens effectively, there are low sugar levels in the blood.<br/> • The fiber in okra help lower bad cholesterol levels – and this invariably contributes to heart health. It also cut the risk of cardiovascular disease and stroke.<br/> • Okra contains lectin, a type of protein. This protein help fight human breast cancer cells.",
                "media": "16M_LJWZ8oEVOivPsBqblFuFWY0tR3Phs",
            },
            "4": {
                "name": "Tomatoes",
                "description": "The tomato is the edible, often red, berry of the nightshade Solanum lycopersicum, commonly known as a tomato plant.",
                "nutrition": "Fresh tomatoes are low in carbs. The carb content consists mainly of simple sugars and insoluble fibers.<br/> • Tomatoes are good source of several vitamins and minerals, such as vitamin C, potassium, vitamin K and folate.<br/> • The main plant compound in tomatoes is lycopene. They also contain beta-carotene, naringenin and chlorogenic acid.",
                "benefits": "Tomatoes and tomato products reduce the risk of heart disease and several cancers. They are also considered to be beneficial for skin health, and may protect against sunburns.<br/> • The fluid and fiber in tomatoes may be helpful if you're prone to constipation.<br/> • Lycopene is  good for eyes. They support vision and protect against eye conditions including cataracts and macular degeneration.",
                "media": "1Hqkk5gIhUEuPARVOUiTISiq9eAFlSTh8",
            },
        },
        "December": {
            "totalNumbers": "4",
            "1": {
                "name": "Ridge Gourd (Luffa)",
                "description": "Luffa or ridge gourd is an elongated, cylindrical fruit pod in the cucurbitaceae/gourd family of vegetables.  Large, lobed leaves are deep green with fine hairs on their surface.",
                "nutrition": "Ridge gourd is one of the very low calorie vegetables. Its delicate, sponge-textured flesh consists of moderate levels of minerals and vitamins in addition to being rich in antioxidants.<br/>• It is also an average sources of B-complex vitamins such as thiamin, niacin (vitamin B-3), pantothenic acid (vitamin B-5), pyridoxine (vitamin B-6) and minerals such as calcium, iron, zinc, potassium, manganese and magnesium.",
                "benefits": "It contains insulin like peptides and alkaloids that helps to reduce the sugar levels in the blood and urine.<br/>• Ridge gourd acts effective in purifying blood. It boosts up and nourishes the liver health and protects the liver from alcohol intoxication.<br/>• It is good for skin care, as the blood purifying qualities in it ensures you to stay clear from pimples and acne.",
                "media": "16u18VV5j0QlO2ByqQhFs_QxUwMW78va3",
            },
            "2": {
                "name": "Cucumber",
                "description": "Cucumber is a widely cultivated plant in the gourd family, Cucurbitaceae. It is a creeping vine that bears cucumiform fruits that are used as vegetables.",
                "nutrition": "Cucumbers are low in calories but high in several important vitamins and minerals.<br/>• Cucumbers contain good amount of fiber and water.",
                "benefits": "Cucumbers contain antioxidants, including flavonoids and tannins, which prevent the accumulation of harmful free radicals and reduce the risk of chronic disease.<br/>• Cucumbers are composed of about 96% water, which increase hydration and help meet the daily fluid needs.<br/>• Cucumbers can be eaten fresh or pickled. They can be enjoyed as a low-calorie snack or used to add flavor in variety of dishes.",
                "media": "1FMHM-US42q_AWZXUbnGhYhUGuUZ-NJ_p",
            },
            "3": {
                "name": "Pumpkin",
                "description": "The leek is a vegetable belonging to the genus Allium, which includes onions, garlic, shallots, scallions, chives, and Chinese onions.",
                "nutrition": "It is also a good source of Vitamin E (Alpha Tocopherol), Thiamin, Niacin, Vitamin B6, Folate, Iron, Magnesium and Phosphorus, and a very good source of Dietary Fiber, Vitamin A, Vitamin C, Riboflavin, Potassium, Copper and Manganese.",
                "benefits": "Pumpkin contains beta-carotene. Your body can turn beta-carotene into Vitamin A, which strengthens your immune system. <br/> • Pumpkin is full of nutrients like fibre, vitamin C, and potassium which lower blood pressure. Additionally, the antioxidants in pumpkin work against the oxidation of bad cholesterol.<br/> • Pumpkin’s health benefits extend even to your skin.  Beta-carotene works as a natural sunscreen for your skin, protecting it from harmful UV rays, and preventing skin cancer from developing.",
                "media": "1wx3rsUMPyr2niUuzkwv5AAxqZT_hTALI",
            },
            "4": {
                "name": "Bitter Melon",
                "description": "Bitter melon, also called bitter gourd or Indian bitter melon, is a climbing shrub that typically grows in countries with a tropical climate. The bitter melon plant is a relatively fast-growing plant characterized by its thin stems, tendrils and bright yellow flowers that only bloom for a day.",
                "nutrition": "Bitter melon is very low in calories. Its pods are rich sources of phytonutrients like dietary fiber, minerals, vitamins, and antioxidants.<br/> • It is an excellent source of health benefiting flavonoids such as β-carotene, α-carotene, lutein, and zeaxanthin.<br/> • It has small amounts of B-complex vitamins such as niacin (vitamin B-3), pantothenic acid (vitamin B-5), pyridoxine (vitamin B-6) and minerals such as iron, zinc, potassium, manganese and magnesium.",
                "benefits": "Bitter melon contains hypoglycemic compounds, which may help improve your body’s ability to utilize sugar for energy.<br/> • Bitter melon also help boost fat metabolism, which may contribute to the prevention of obesity, which is one of the risk factors of diabetes.<br/> • Bitter melon contribute to better immune function, as it is filled with numerous antioxidants and other essential nutrients.",
                "media": "1lq1w2ulN2VuaBrOZnMpCdJ-L1dI9JaEI",
            },
        },
    }
    return (VegetablesContent);
}