export default function VegetablesContent() {
    var FruitContent = {
        "January": {
            "totalNumbers": "4",
            "1": {
                "name": "Stawberries",
                "description": "•  A beautiful and delicious small red fruit. Strawberries are available fresh,freeze-dried, and in jellies, syrups, and jams",
                "nutrition": "• It is packed with vitamins C, fiber, and particularly high levels of antioxidants known as polyphenols, strawberries are a sodium-free, fat-free, cholesterol-free, low-calorie food.",
                "benefits": "• The powerful antioxidants in strawberries may work against free radicals, inhibiting tumor growth and decreasing inflammation in the body. <br/> • Strawberries are a low glycemic index food and high in fiber, which helps to regulate blood sugar and keep it stable by avoiding extreme highs and lows.<br/> • It protects from various eye problems, prevent Heart diseases & cancer risk. It is one of the best fruit for immunity booster.",
                "media": "1Qkq6lhE7Z_ZTjVfdhHtN-EPdyiIOHkLe",
            },
            "2": {
                "name": "Orange",
                "description": "•  Generally an orange should have smoothly textured skin and be firm and heavy for its size. These will have higher juice content than those that are either spongy or lighter in weight.",
                "nutrition": "• Oranges, like other citrus fruits, are an excellent source of vitamin-C.Orange fruit contains a variety of phytochemicals.Oranges also contain very good levels of vitamin-A, and other flavonoid antioxidants such as a and ß -carotenes, ß -cryptoxanthin, zeaxanthin and lutein. These compounds have been known to have antioxidant properties.",
                "benefits": "• Antioxidants in oranges help protect skin from free radical damage known to cause signs of aging.<br/> • Drinking orange juice regularly prevents kidney diseases and reduce the risk of kidney stones.<br/> • Since they’re full of soluble fiber, oranges are helpful in lowering cholesterol.<br/> • Oranges are rich in citrus limonoids, proven to help fight a number of varieties of cancer including that of the lung, breast, stomach and colon.",
                "media": "139s4Z00FNPdvO5HzkUAHWPsECJrXDqsC",
            },
            "3": {
                "name": "Pineapple",
                "description": "• The pineapple is a tropical plant with an edible multiple fruit consisting of coalesced berries, also called pineapples.",
                "nutrition": "•  Pineapples contain high amounts of vitamin C.  and manganese.Pineapples are tropical fruit that are rich in vitamins, enzymes and antioxidants.",
                "benefits": "• Pineapple mostly recommends to injured patients because its supports injuries healing process. <br/> • It is beneficial for preventing cancer risk, keeps your blood pressure in control. <br/> • In addition to having lots of vitamin C, pineapple’s bromelain may help reduce mucus in the throat and nose, i.e helpful on Coughs and Colds.<br/> • Pineapples can help reduce the risk of macular degeneration, a disease that affects the eyes as people age, due in part to its high amount of vitamin C and the antioxidants it contains.<br/> • Adding more pineapple to your diet will give you more of the antioxidants you need to slow the development of this sight-robbing condition.<br/>",
                "media": "1t8vIHjQK0fjqZgtWM55LSivc5-UCMJtp",
            },
            "4": {
                "name": "Kiwi",
                "description": "•  Kiwis are small fruits that pack a lot of flavor and plenty of health benefits.Their green flesh is sweet and tangy.",
                "nutrition": "•  It’s also full of nutrients like vitamin C, vitamin K, vitamin E, folate, and potassium. They also have a lot of antioxidants and are a good source of fiber.Kiwis have plenty of fiber, which is already good for digestion.",
                "benefits": "•  Fruits provide an extra boost to our immune system and reduce the likelihood of developing cold- or flu-like illnesses. They can also help us to manage our blood pressure.<br/> • The high amount of vitamin C and antioxidants that kiwis contain can actually help treat people with asthma.<br/> • Eating two to three kiwis a day significantly lowered the risk of blood clotting. They were also found to reduce the amount of fat in the blood.<br/> ",
                "media": "1YCQtj7Ql6XSlL7ihx36yHf_zWZsYL_T3",
            },
        },
        "February": {
            "totalNumbers": "3",
            "1": {
                "name": "Chikoo (Sapota)",
                "description": "• The fruit is brown colored large berry which has 2 to 5 big, shiny and black colored seeds. The flesh is pale brown in color, smooth and buttery in feel with exceptionally sweet taste.",
                "nutrition": "• Chikoo is a good source of dietary fiber.Chikoo contains a number of minerals including iron, magnesium, calcium, phosphorus, copper, and potassium.<br/>• It contains vitamin A, vitamin C.Chikoo is high in calories, with about 83 calories per 100 grams.",
                "benefits": "•  The dietary fiber prevents constipation.<br/> • Vitamins C and A help to keep the mucus membranes and skin healthy. Vitamin C also boosts immunity, prevents infections, and scavenges free radicals.<br/>  • The magnesium, calcium, and phosphorus help keep bones strong while the magnesium benefits the heart and blood vessels.<br/> • Chikoo juice helps to maintain healthy weight and lowers the risk of diabetes and heart disease. It also activates performance of the intestine.<br/> ",
                "media": "1Wj7O5s-ByygsxprPOzdbZjpK7f7VpDoE",
            },
            "2": {
                "name": "Guava",
                "description": "•  The fruit is oval in shape with light green or yellow skin and contain edible seeds. Fresh guavas taste mellow and mildly sweet. Its lack of acidity gives the fruit a musky taste reminiscent of an unsweetened white peach.",
                "nutrition": "• Guava is low in calories and fats but carry several vital vitamins and minerals.<br/> • Guava fruits are amazingly rich in antioxidants, vitamin C, potassium, and fiber. This remarkable nutrient content gives them many health benefits.",
                "benefits": "• Compounds within guava, like lycopene, vitamin C, quercetin, and polyphenols, act as anti-cancer and anti-tumor agents.<br/> • The high vitamin C content in guava helps it play an essential role in improving your overall immune system.<br/> • Guava contains strong antioxidant powers, especially red guava. These compounds help to neutralize free radicals, which can cause damage to skin cells and premature aging. ",
                "media": "1Bf86INm6ates71Eb8texOYnUiWLudlxJ",
            },
            "3": {
                "name": "Grapes",
                "description": "•  Grapes come in different colors and forms. There are red, green, and purple grapes. Grapes are easily available in the markets throughout the year.",
                "nutrition": "• Grapes are a powerhouse of antioxidants – they contain a wide range of phytonutrients right from carotenoids to polyphenols.<br/> • Grapes are also loaded with vitamins and essential minerals such as Vitamins A, B-6, B-12, C and D, calcium, iron and magnesium.",
                "benefits": "• Grapes contain high levels of beneficial plant compounds, which may help protect against certain types of cancer.<br/> • Red grapes are rich in nutrients such as Potassium.This mineral is necessary for maintaining healthy blood pressure levels.<br/> • Compounds found in grapes may help protect against high cholesterol levels by decreasing cholesterol absorption.<br/>",
                "media": "1oC8nZtZ_-rXND4dpG1up7eCCKUmY7WY5",
            },
        },
        "March": {
            "totalNumbers": "3",
            "1": {
                "name": "Watermelon",
                "description": "• Watermelon is a delicious and refreshing fruit that's also good for you. It’s a type of edible fruit, they are 92% water. About 6% of a watermelon is sugar, which makes it very sweet.",
                "nutrition": "• One cup of watermelon will provide the following percentage of daily vitamins:<br/>  17 percent of vitamin A <br/> 21 percent of vitamin C <br/>   2 percent of iron <br/>  1 percent of calcium <br/> • Watermelon also contains thiamine, riboflavin, niacin, vitamin B-6, folate, pantothenic acid, magnesium and phosphorus etc. ",
                "benefits": "• Watermelons help with overall hydration. Additionally, their juice is full of good electrolytes. This can even help prevent heat stroke. <br/>  • Watermelon's high levels of lycopene are very effective at protecting cells from damage and may help lower the risk of heart disease. <br/>  • The watermelon contains fiber, which encourages a healthy digestive tract and helps keep you regular. <br/> • Watermelons may be helpful in reducing the risk of cancer through their antioxidant properties. Lycopene in particular has been linked to reducing prostate cancer cell proliferation. ",
                "media": "1PQ0_L3dB3BDN7I4jpDTi4k5HzkO2JACk",
            },
            "2": {
                "name": "Banana",
                "description": "•  An instant energy booster, banana is one fruit that is commonly available across the globe. Bananas are great super food which provides us with energy, make us feel full and provide our body with essential nutrients and high amount of fiber.",
                "nutrition": "• Bananas are an excellent source of potassium and supply vitamin B6, fibre and carbohydrate, and some vitamin C. Since they have a lower water content than most fruit, bananas typically have more calories as well as a higher sugar content compared to other non-tropical fruits. <br/> • A 100g serving provides 81 kcal, 20.3g of carbohydrate, 1.4g fibre and 18.1g of natural sugar.",
                "benefits": "• Bananas are loaded with valuable micronutrients, especially potassium,helping to regulate heart function as well as fluid balance – a key factor in regulating blood pressure. <br/> • Increasing the consumption of fibre-rich foods such as bananas can lower the risk of both cardiovascular disease (CVD) and coronary heart disease (CHD). ",
                "media": "1EOirAalgKdC-D5_6aJRSt66l08qu2pDU",
            },
            "3": {
                "name": "Pineapple",
                "description": "• The pineapple is a tropical plant with an edible multiple fruit consisting of coalesced berries, also called pineapples.",
                "nutrition": "•  Pineapples contain high amounts of vitamin C.  and manganese.Pineapples are tropical fruit that are rich in vitamins, enzymes and antioxidants.",
                "benefits": "• Pineapple mostly recommends to injured patients because its supports injuries healing process. <br/> • It is beneficial for preventing cancer risk, keeps your blood pressure in control. <br/> • In addition to having lots of vitamin C, pineapple’s bromelain may help reduce mucus in the throat and nose, i.e helpful on Coughs and Colds.<br/> • Pineapples can help reduce the risk of macular degeneration, a disease that affects the eyes as people age, due in part to its high amount of vitamin C and the antioxidants it contains.<br/> • Adding more pineapple to your diet will give you more of the antioxidants you need to slow the development of this sight-robbing condition.<br/>",
                "media": "1t8vIHjQK0fjqZgtWM55LSivc5-UCMJtp",
            },
        },
        "April": {
            "totalNumbers": "4",
            "1": {
                "name": "Jackfruit",
                "description": "• Jackfruit is absolutely one of a kind tropical fruit recognized for its unique shape, and size. The fruity flavor of its sweet arils (bulbs) can be appreciated from a distance.  It has a green, spiky exterior while the interior is made up of many pale-yellow bulbs, which are edible. The seeds can also be cooked, eaten on their own, or ground into flour. ",
                "nutrition": "• Jackfruit is rich in vitamin A, vitamin C, magnesium, vitamin B6 and fiber. ",
                "benefits": "•  The fruit made of soft, easily digestible flesh (arils) made up of simple sugars like fructose and sucrose that when eaten replenishes energy and revitalizes the body instantly. <br/> • Jackfruit is rich in dietary fiber, which makes it a good bulk laxative. The fiber content helps protect the colon mucous membrane by binding to and eliminating cancer-causing chemicals from the colon. <br/> • Jackfruit is a good source of antioxidant vitamin-C,Consumption of foods rich in vitamin-C helps the body develop resistance against infectious agents and scavenge harmful free radicals.  ",
                "media": "1zb12UyrtRA_zujLsAm2oPXF44RPQKq5t",
            },
            "2": {
                "name": "Orange",
                "description": "•  Generally an orange should have smoothly textured skin and be firm and heavy for its size. These will have higher juice content than those that are either spongy or lighter in weight.",
                "nutrition": "• Oranges, like other citrus fruits, are an excellent source of vitamin-C.Orange fruit contains a variety of phytochemicals.Oranges also contain very good levels of vitamin-A, and other flavonoid antioxidants such as a and ß -carotenes, ß -cryptoxanthin, zeaxanthin and lutein. These compounds have been known to have antioxidant properties.",
                "benefits": "• Antioxidants in oranges help protect skin from free radical damage known to cause signs of aging.<br/> • Drinking orange juice regularly prevents kidney diseases and reduce the risk of kidney stones.<br/> • Since they’re full of soluble fiber, oranges are helpful in lowering cholesterol.<br/> • Oranges are rich in citrus limonoids, proven to help fight a number of varieties of cancer including that of the lung, breast, stomach and colon.",
                "media": "139s4Z00FNPdvO5HzkUAHWPsECJrXDqsC",
            },
            "3": {
                "name": "Watermelon",
                "description": "• Watermelon is a delicious and refreshing fruit that's also good for you. It’s a type of edible fruit, they are 92% water. About 6% of a watermelon is sugar, which makes it very sweet.",
                "nutrition": "• One cup of watermelon will provide the following percentage of daily vitamins:<br/>  17 percent of vitamin A <br/> 21 percent of vitamin C <br/>   2 percent of iron <br/>  1 percent of calcium <br/> • Watermelon also contains thiamine, riboflavin, niacin, vitamin B-6, folate, pantothenic acid, magnesium and phosphorus etc. ",
                "benefits": "• Watermelons help with overall hydration. Additionally, their juice is full of good electrolytes. This can even help prevent heat stroke. <br/>  • Watermelon's high levels of lycopene are very effective at protecting cells from damage and may help lower the risk of heart disease. <br/>  • The watermelon contains fiber, which encourages a healthy digestive tract and helps keep you regular. <br/> • Watermelons may be helpful in reducing the risk of cancer through their antioxidant properties. Lycopene in particular has been linked to reducing prostate cancer cell proliferation. ",
                "media": "1PQ0_L3dB3BDN7I4jpDTi4k5HzkO2JACk",
            },
            "4": {
                "name": "Apricots",
                "description": "• This yellowish-orange fleshy fruit is quite a curious little thing. The tiny hairs on the outer skin lend a soft furry texture, and can be eaten without having to be peeled. It’s also one of the healthiest fruits in the world, with loads of benefits.",
                "nutrition": "• The health benefits of apricots are due to the significant content of vitamins, including vitamins A, C, K, E, and niacin. <br/>  • Apricots also have a good mineral content. The minerals found in apricots are potassium, copper manganese, magnesium, and phosphorous. They are also a very good source of dietary fiber, like most fruits. ",
                "benefits": "• Apricots are rich in antioxidants. The carotenoids and antioxidants protect our bodies from the dangerous free radicals and prevent the damage of cells. Apricots are also rich in vitamins A and C which are powerful antioxidants that fight cancer diseases and boost the immune system. <br/>  • Apricots are rich in fiber and are,therefore, good for smooth and proper bowel movements.Fiber also activates the peristaltic motion of the digestive tract. Apricots contain high amounts of pectin and cellulose that act as a mild laxative, thus helping in the treatment of constipation. <br/> • Iron and copper abundance in apricots help in the formation of hemoglobin and thus helps in the treatment of anemia. ",
                "media": "1bRsKZbNt3VWoAJS8CSa4R1pR7luS9ek4",
            },
        },
        "May": {
            "totalNumbers": "3",
            "1": {
                "name": "Papaya",
                "description": "• Papayas grow in tropical climates and are also known as papaws or pawpaws. Their sweet taste, vibrant color, and the wide variety of health benefits they provide make them a popular fruit.The papaya, a previously exotic and rare fruit, is now available at most times of the year.",
                "nutrition": "• Papayas are an excellent source of vitamin C, and one single medium fruit provides 224 percent of recommended daily intake. <br/>  Papayas are also a good source of folate,vitamin A , magnesium,copper,pantothenic acid and fiber.They also have B vitamins, alpha and beta-carotene, lutein and zeaxanthin, vitamin E, calcium, potassium, vitamin K, and lycopene, the powerful antioxidant most commonly associated with tomatoes.  ",
                "benefits": "• Consuming the antioxidant beta-carotene, found in papayas, may reduce cancer risk. Among younger men, diets rich in beta-carotene may play a protective role against prostate cancer. <br/> • Adequate vitamin K consumption is important for good health, as it improves calcium absorption and may reduce urinary excretion of calcium, meaning there is more calcium in the body to strengthen and rebuild bones. <br/> • Papaya is also high in fiber and water content, both of which help to prevent constipation and promote regularity and a healthy digestive tract. ",
                "media": "1fRawi5vhewPc8QdTnQm0XV2iyJZbV38W",
            },
            "2": {
                "name": "Litchi",
                "description": "• It has a round or oval shape with a pinkish-brown rind, translucent to white flesh, and an inedible seed. It may have a short shelf life, but this juicy summer treat has more than just taste to offer. ",
                "nutrition": "•  Litchis contain an impressive array of vitamins, fiber and antioxidants. <br/> • Litchis are a decent source of several vitamins and minerals, especially vitamin C, Copper, Potassium. ",
                "benefits": "•  The nutrients in lychee, including magnesium, copper, iron, vitamin C, manganese and folate, are required for blood circulation and formation. <br/>  • Litchi is rich source antioxidants Vitamin C. Antioxidants are effective to protect from free radicals and oxidative stress. So it protects from degenerative disease and prevents arthritis. <br/>  • Litchi contains high amount of antioxidants which is effective to prevent early ageing. <br/> • Litchi contains high amount of dietary fiber which proves best nutrient that promote cardiovascular health. <br/>  ",
                "media": "1MpOv-74dDvrmQ94OOVtgd4MfkEPGcVFC",
            },
            "3": {
                "name": "Jackfruit",
                "description": "• Jackfruit is absolutely one of a kind tropical fruit recognized for its unique shape, and size. The fruity flavor of its sweet arils (bulbs) can be appreciated from a distance.  It has a green, spiky exterior while the interior is made up of many pale-yellow bulbs, which are edible. The seeds can also be cooked, eaten on their own, or ground into flour. ",
                "nutrition": "• Jackfruit is rich in vitamin A, vitamin C, magnesium, vitamin B6 and fiber. ",
                "benefits": "•  The fruit made of soft, easily digestible flesh (arils) made up of simple sugars like fructose and sucrose that when eaten replenishes energy and revitalizes the body instantly. <br/> • Jackfruit is rich in dietary fiber, which makes it a good bulk laxative. The fiber content helps protect the colon mucous membrane by binding to and eliminating cancer-causing chemicals from the colon. <br/> • Jackfruit is a good source of antioxidant vitamin-C,Consumption of foods rich in vitamin-C helps the body develop resistance against infectious agents and scavenge harmful free radicals.  ",
                "media": "1zb12UyrtRA_zujLsAm2oPXF44RPQKq5t",
            },
        },
        "June": {
            "totalNumbers": "3",
            "1": {
                "name": "Mango",
                "description": "• Mango is one of the delicious seasonal fruits grown in the tropics. Internally, its flesh (mesocarp) is juicy, orange-yellow in color with numerous soft fibrils radiating from its centrally placed flat, oval-shaped stone (enveloping a single large kidney-shaped seed). Its flavor is pleasant and rich and tastes sweet with a mild tartness. ",
                "nutrition": "• This fruit offers a healthy dose of vitamins, minerals and enzymes that are beneficial for our health. And that's not it, the mighty mango is a great high-fibre and high-antioxidant food too. Mangoes are high in the antioxidants beta-carotene and vitamin C.",
                "benefits": "•  Mangoes play an important role in reducing problems like indigestion and excess acidity. Mangoes comprise digestive enzymes that are known to promote natural, efficient digestion. <br/> • Mangoes are rich in beta-carotene, which is a powerful antioxidant known to reduce the effects of free-radical damage in our body, including eyes and the skin. <br/>  • Consuming mangoes fulfill the requirement of vitamin C and vitamin A in our body and keep the immune system healthy and strong. Vitamin C helps to reduce the incidence of cold and flu, whereas vitamin A gives us additional protection against the free radicals harming our internal systems. <br/>  • Mangoes can help slow down the process of natural ageing; all thanks to vitamins A and C that are present in high amounts in mangoes. ",
                "media": "10YYfqIATlA8pe5jFQJu8PPLKP-Z8wDCq",
            },
            "2": {
                "name": "Cherry",
                "description": "•  Cherries are drupe fruits with a central “stony-hard” seed surrounded by fleshy edible pulp.They come in small sizes, measuring about 2 cm in diameter. Externally they covered by bright 'shiny' red or purple, thin peel.",
                "nutrition": "• Cherries are fat-, cholesterol- and sodium-free.One cup of cherries is less than 90 calories. That same cup of cherries has 3 grams of fiber. <br/>  • Cherries are a good source of vitamin C,vitamin A, calcium, protein and iron,Potassium.Cherries are one of the top antioxidant-rich foods. ",
                "benefits": "•  Cherries are a potent source of antioxidants and anti-inflammatory compounds. These cellular bodyguards slow down aging and ward off chronic illnesses—including heart disease, cancer, Alzheimer’s, diabetes, and obesity. <br/> • Tart cherries in particular are one of the few food sources of melatonin, a hormone that helps control your sleep-wake cycles. <br/> • Several studies have suggested that cherry consumption is beneficial for osteoarthritis sufferers. Regularly incorporating cherries or 100% cherry juice into your meal or snack routine may help lessen your joint pain. <br/> • Drinking tart cherry juice can help lower total cholesterol, including the “bad” type, known as LDL. That’s key because every 1% reduction in cholesterol lowers the risk of heart disease by 2%. <br/>  ",
                "media": "1AV4lXwHzH2O1b25uf3pq5xTIEmEgSjdN",
            },
            "3": {
                "name": "Litchi",
                "description": "• It has a round or oval shape with a pinkish-brown rind, translucent to white flesh, and an inedible seed. It may have a short shelf life, but this juicy summer treat has more than just taste to offer. ",
                "nutrition": "•  Litchis contain an impressive array of vitamins, fiber and antioxidants. <br/> • Litchis are a decent source of several vitamins and minerals, especially vitamin C, Copper, Potassium. ",
                "benefits": "•  The nutrients in lychee, including magnesium, copper, iron, vitamin C, manganese and folate, are required for blood circulation and formation. <br/>  • Litchi is rich source antioxidants Vitamin C. Antioxidants are effective to protect from free radicals and oxidative stress. So it protects from degenerative disease and prevents arthritis. <br/>  • Litchi contains high amount of antioxidants which is effective to prevent early ageing. <br/> • Litchi contains high amount of dietary fiber which proves best nutrient that promote cardiovascular health. <br/>  ",
                "media": "1MpOv-74dDvrmQ94OOVtgd4MfkEPGcVFC",
            },
        },
        "July": {
            "totalNumbers": "3",
            "1": {
                "name": "Plum (Aloo Bukhara)",
                "description": "• The plum is a wonderful, juicy fruit that belongs botanically to the family of Rosaceae. The plum fruits differ in color and size according to the region of origin. ",
                "nutrition": "• Plums are extremely nutritious, with a variety of health benefits to offer. <br/> They contain many vitamins and minerals, in addition to fiber and antioxidants.Plums are relatively low in calories, but contain a fair amount of important vitamins and minerals. One plum contains the following nutrients - <br/> Calories- 30 <br/> Carbs- 8 grams <br/> Fiber- 1 gram <br/>  Sugars- 7 grams <br/> Vitamin A- 5% of the RDI <br/> Vitamin C- 10% of the RDI <br/> Vitamin K- 5% of the RDI <br/> Potassium- 3% of the RDI <br/> Copper- 2% of the RDI <br/> Manganese- 2% of the RDI <br/> ",
                "benefits": "• The compounds sorbitol and isatin, found in plums, help in regulating the functioning of the digestive system and in relieving constipation. <br/> • The vitamin C in the plum helps the body develop resistance against infectious agents, counter inflammation and free radicals. <br/> • Plums also help in maintaining the heart health. They contain antioxidants that help to get rid of the free radicals and prevent cholesterol oxidation. <br/>  • Vitamin A found in plums is also known to protect from oral and cavity cancer. Plums are particularly good in preventing breast cancer. ",
                "media": "19310nhQSn8o7GW72AG5R6l6MDC8szf_J",
            },
            "2": {
                "name": "Mango",
                "description": "• Mango is one of the delicious seasonal fruits grown in the tropics. Internally, its flesh (mesocarp) is juicy, orange-yellow in color with numerous soft fibrils radiating from its centrally placed flat, oval-shaped stone (enveloping a single large kidney-shaped seed). Its flavor is pleasant and rich and tastes sweet with a mild tartness. ",
                "nutrition": "• This fruit offers a healthy dose of vitamins, minerals and enzymes that are beneficial for our health. And that's not it, the mighty mango is a great high-fibre and high-antioxidant food too. Mangoes are high in the antioxidants beta-carotene and vitamin C.",
                "benefits": "•  Mangoes play an important role in reducing problems like indigestion and excess acidity. Mangoes comprise digestive enzymes that are known to promote natural, efficient digestion. <br/> • Mangoes are rich in beta-carotene, which is a powerful antioxidant known to reduce the effects of free-radical damage in our body, including eyes and the skin. <br/>  • Consuming mangoes fulfill the requirement of vitamin C and vitamin A in our body and keep the immune system healthy and strong. Vitamin C helps to reduce the incidence of cold and flu, whereas vitamin A gives us additional protection against the free radicals harming our internal systems. <br/>  • Mangoes can help slow down the process of natural ageing; all thanks to vitamins A and C that are present in high amounts in mangoes. ",
                "media": "10YYfqIATlA8pe5jFQJu8PPLKP-Z8wDCq",
            },
            "3": {
                "name": "Peach",
                "description": "•  Peaches are juicy and versatile summer fruits.",
                "nutrition": "•Peaches store a broad range of nutrients that are vital for the healthy functioning of the body. <br/> • Peaches are a rich source of potassium, vitamin A, beta-carotene, and vitamin C (ascorbic acid). They are also a good source of vitamin E (alpha-tocopherol), vitamin K (phylloquinone), vitamin B1 (thiamin), vitamin B2 (riboflavin), vitamin B3 (niacin), vitamin B-6, and folate. <br/> • Peaches offer a rich treasure of minerals such as calcium, magnesium, iron, phosphorous, zinc, and copper. ",
                "benefits": "• Fruit_Benefits",
                "media": "1erO67ClhROLNL6aeng76CqjewU4rArW_",
            },
        },
        "August": {
            "totalNumbers": "4",
            "1": {
                "name": "Mango",
                "description": "• Mango is one of the delicious seasonal fruits grown in the tropics. Internally, its flesh (mesocarp) is juicy, orange-yellow in color with numerous soft fibrils radiating from its centrally placed flat, oval-shaped stone (enveloping a single large kidney-shaped seed). Its flavor is pleasant and rich and tastes sweet with a mild tartness. ",
                "nutrition": "• This fruit offers a healthy dose of vitamins, minerals and enzymes that are beneficial for our health. And that's not it, the mighty mango is a great high-fibre and high-antioxidant food too. Mangoes are high in the antioxidants beta-carotene and vitamin C.",
                "benefits": "•  Mangoes play an important role in reducing problems like indigestion and excess acidity. Mangoes comprise digestive enzymes that are known to promote natural, efficient digestion. <br/> • Mangoes are rich in beta-carotene, which is a powerful antioxidant known to reduce the effects of free-radical damage in our body, including eyes and the skin. <br/>  • Consuming mangoes fulfill the requirement of vitamin C and vitamin A in our body and keep the immune system healthy and strong. Vitamin C helps to reduce the incidence of cold and flu, whereas vitamin A gives us additional protection against the free radicals harming our internal systems. <br/>  • Mangoes can help slow down the process of natural ageing; all thanks to vitamins A and C that are present in high amounts in mangoes. ",
                "media": "10YYfqIATlA8pe5jFQJu8PPLKP-Z8wDCq",
            },
            "2": {
                "name": "Custard Apple",
                "description": "• The fruit is soft and chewy with a hard exterior. The flesh is white in color and has a creamy texture. Custard apple with its high calories and natural sugars are great as a dessert and as a nutritious snack. ",
                "nutrition": "•  Custard apples are rich in anti-oxidants like vitamin C. It is also rich in calcium, magnesium, iron, niacin & potassium. ",
                "benefits": "• Custard apple is great for healthy skin, healthy hair and better eyesight. It plays a role in moisturisation and anti-aging. <br/> • Custard apples are good for those who need to gain weight. A mixture of honey and custard apple when consumed regularly will help add on the required weight and those much required calories. <br/> • Custard apple helps develop the brain, nervous system and immune system of a fetus effectively. Regular consumption of custard apple also reduces the risk of miscarriage during pregnancy and minimizes the extent of labor pain during childbirth. ",
                "media": "12L0QxlSSrsoyE1KvLvDj9IVDI3AUonh1",
            },
            "3": {
                "name": "Muskmelon",
                "description": "• Juicy, fleshy and aromatic, muskmelon is one of the most loved and cultivated fruits of India. ",
                "nutrition": "• Muskmelons are very low in calories (100 g fruit has just 34 calories) and fats. Nonetheless, the fruit is rich in numerous health promoting polyphenolic plant derived compounds, vitamins, and minerals that are absolute for optimum health. <br/> • The fruit is an excellent source of Vitamin-A,  one of the highest among cucurbita fruits. <br/> • It is also rich in antioxidant flavonoids such as beta-carotene, lutein, zeaxanthin, and cryptoxanthin. ",
                "benefits": "• Muskmelons are rich in potassium which helps in regulating the blood pressure and keeps hypertension at bay. <br/> • They have high doses of vitamin A and beta carotene, which helps sharpen the eye sight as well as reduce the risk of developing cataracts. <br/> • Musk melons have negligible fat content in them. They also contain the good carbohydrates derived from sugars which are easily broken down by the body and helps in weight loss. <br/>  • They stimulate and increase the white blood cells which help in destroying viruses and bacteria. They also prevent premature ageing of cells. ",
                "media": "1YiERtNE589_BuqsAU46QhSCXDLh244q_",
            },
            "4": {
                "name": "Litchi",
                "description": "• It has a round or oval shape with a pinkish-brown rind, translucent to white flesh, and an inedible seed. It may have a short shelf life, but this juicy summer treat has more than just taste to offer. ",
                "nutrition": "•  Litchis contain an impressive array of vitamins, fiber and antioxidants. <br/> • Litchis are a decent source of several vitamins and minerals, especially vitamin C, Copper, Potassium. ",
                "benefits": "•  The nutrients in lychee, including magnesium, copper, iron, vitamin C, manganese and folate, are required for blood circulation and formation. <br/>  • Litchi is rich source antioxidants Vitamin C. Antioxidants are effective to protect from free radicals and oxidative stress. So it protects from degenerative disease and prevents arthritis. <br/>  • Litchi contains high amount of antioxidants which is effective to prevent early ageing. <br/> • Litchi contains high amount of dietary fiber which proves best nutrient that promote cardiovascular health. <br/>  ",
                "media": "1MpOv-74dDvrmQ94OOVtgd4MfkEPGcVFC",
            },
        },
        "September": {
            "totalNumbers": "3",
            "1": {
                "name": "Guava",
                "description": "•  The fruit is oval in shape with light green or yellow skin and contain edible seeds. Fresh guavas taste mellow and mildly sweet. Its lack of acidity gives the fruit a musky taste reminiscent of an unsweetened white peach.",
                "nutrition": "• Guava is low in calories and fats but carry several vital vitamins and minerals.<br/> • Guava fruits are amazingly rich in antioxidants, vitamin C, potassium, and fiber. This remarkable nutrient content gives them many health benefits.",
                "benefits": "• Compounds within guava, like lycopene, vitamin C, quercetin, and polyphenols, act as anti-cancer and anti-tumor agents.<br/> • The high vitamin C content in guava helps it play an essential role in improving your overall immune system.<br/> • Guava contains strong antioxidant powers, especially red guava. These compounds help to neutralize free radicals, which can cause damage to skin cells and premature aging. ",
                "media": "1Bf86INm6ates71Eb8texOYnUiWLudlxJ",
            },
            "2": {
                "name": "Passion Fruit",
                "description": "•Passion fruit is a nutritious tropical fruit. <br/> It's gaining popularity, especially among those who are health conscious. It has a tough outer rind and juicy, seed-filled center. <br/> There are several types, which can vary in size and color. The most commonly available are the purple and yellow varieties. ",
                "nutrition": "• Passion fruit is a good source of nutrients, especially fiber, vitamin C and vitamin A. <br/> • A single purple passion fruit of about 18 grams contains : <br/> Calories: 17 <br/> Fiber: 2 grams <br/> Vitamin C: 9% of the RDI <br/> Vitamin A: 8% of the RDI <br/> Iron: 2% of the RDI <br/>  Potassium: 2% of the RDI <br/> • It's also rich in beneficial plant compounds, including carotenoids and polyphenols ",
                "benefits": "•  Passion fruit has a low glycemic index (GI) and high fibre content (10.4%). This makes it a great fruit to maintain insulin levels for diabetics. <br/> • Passion fruit has many types of antioxidants in it like Vitamin A, Vitamin C, riboflavin and carotene. These antioxidants reduce the production of free radicals in our body. <br/> • Step up your immunity with the jelly, juice or squash of passion fruit. It also  has iron which increases haemoglobin in our red blood cells. ",
                "media": "17UAgwtAfGVdpLzjWPHRcBpp2JmLWZ5Zw",
            },
            "3": {
                "name": "Custard Apple",
                "description": "• The fruit is soft and chewy with a hard exterior. The flesh is white in color and has a creamy texture. Custard apple with its high calories and natural sugars are great as a dessert and as a nutritious snack. ",
                "nutrition": "•  Custard apples are rich in anti-oxidants like vitamin C. It is also rich in calcium, magnesium, iron, niacin & potassium. ",
                "benefits": "• Custard apple is great for healthy skin, healthy hair and better eyesight. It plays a role in moisturisation and anti-aging. <br/> • Custard apples are good for those who need to gain weight. A mixture of honey and custard apple when consumed regularly will help add on the required weight and those much required calories. <br/> • Custard apple helps develop the brain, nervous system and immune system of a fetus effectively. Regular consumption of custard apple also reduces the risk of miscarriage during pregnancy and minimizes the extent of labor pain during childbirth. ",
                "media": "12L0QxlSSrsoyE1KvLvDj9IVDI3AUonh1",
            },
        },
        "October": {
            "totalNumbers": "3",
            "1": {
                "name": "Pomegranate",
                "description": "• Pomegranate fruit is one of the most popular, nutritionally rich fruit with unique flavor, taste, and heath promoting characteristics.",
                "nutrition": "• Pomegranates have an impressive nutrient profile-one cup of arils (174 grams) contains : <br/> Fiber: 7 grams <br/>  Protein: 3 grams <br/> Vitamin C: 30% of the RDI <br/> Vitamin K: 36% of the RDI <br/> Folate: 16% of the RDI <br/> Potassium: 12% of the RDI <br/> ",
                "benefits": "•  Pomegranate is rich in anti-oxidants and thus protects our body from free radicals, which are responsible for premature ageing. <br/> • Pomegranate helps to pump the level of oxygen in our blood. Due to anti-oxidants present in pomegranate, it fights free radicals, reduces cholesterol and prevents blood clot. <br/> • Punicic acid is one of the main constituents of pomegranate that help lower cholesterol, triglycerides and reduce blood pressure. ",
                "media": "1UthNVjI_RI4XDqxgQDAGJwLVTxT1yC8M",
            },
            "2": {
                "name": "Pear",
                "description": "• Pears have a characteristic shape, with a round and wide bottom and a tapering top. They come in different colors like green, brown, red and yellow.",
                "nutrition": "•Pears are free of fat and cholesterol and very low in sodium. A medium-sized pear has 6 grams of fiber. <br/> • Eating one medium pear provides 12 percent of daily vitamin C needs, as well as 10 percent of vitamin K, 6 percent of potassium and smaller amounts of calcium, iron, magnesium, riboflavin, vitamin B-6, and folate. ",
                "benefits": "•  The presence of vitamin C, vitamin K, and copper in pears fights against free radicals that damage our body cells. <br/> • One of the best benefits of pears include the presence of fiber, which reduces the cholesterol in the body and thereby protects us from heart diseases. <br/>  • The high content of fiber present in pears binds to the carcinogenic cells by removing them and prevents colon cancer. <br/> • Pears, when compared with other fruits, have less chance of allergenic reactions when eaten and thus are one of the few fruits that can be given to infants. ",
                "media": "1so6Ca5CwphGw8z9XhncldiU8mxRRtYy0",
            },
            "3": {
                "name": "Passion Fruit",
                "description": "•Passion fruit is a nutritious tropical fruit. <br/> It's gaining popularity, especially among those who are health conscious. It has a tough outer rind and juicy, seed-filled center. <br/> There are several types, which can vary in size and color. The most commonly available are the purple and yellow varieties. ",
                "nutrition": "• Passion fruit is a good source of nutrients, especially fiber, vitamin C and vitamin A. <br/> • A single purple passion fruit of about 18 grams contains : <br/> Calories: 17 <br/> Fiber: 2 grams <br/> Vitamin C: 9% of the RDI <br/> Vitamin A: 8% of the RDI <br/> Iron: 2% of the RDI <br/>  Potassium: 2% of the RDI <br/> • It's also rich in beneficial plant compounds, including carotenoids and polyphenols ",
                "benefits": "•  Passion fruit has a low glycemic index (GI) and high fibre content (10.4%). This makes it a great fruit to maintain insulin levels for diabetics. <br/> • Passion fruit has many types of antioxidants in it like Vitamin A, Vitamin C, riboflavin and carotene. These antioxidants reduce the production of free radicals in our body. <br/> • Step up your immunity with the jelly, juice or squash of passion fruit. It also  has iron which increases haemoglobin in our red blood cells. ",
                "media": "17UAgwtAfGVdpLzjWPHRcBpp2JmLWZ5Zw",
            },
        },
        "November": {
            "totalNumbers": "3",
            "1": {
                "name": "Dates",
                "description": "• Dates are the fruit of the date palm tree, which is grown in many tropical regions of the world. A wrinkled skin indicates they are dried, whereas a smooth skin indicates freshness. <br/> Depending on the variety, fresh dates are fairly small in size and range in color from bright red to bright yellow. Medjool and Deglet Noor dates are the most commonly consumed varieties. ",
                "nutrition": "• Since they’re dried, their calorie content is higher than most fresh fruit. The calorie content of dates is similar to that of other dried fruits, such as raisins and figs. <br/> • Most of the calories in dates come from carbs. The rest are from a very small amount of protein. Despite their calories, dates contain some important vitamins and minerals in addition to a significant amount of fiber. <br/> • A 3.5-ounce (100-gram) serving provides the following nutrients (1): <br/> Calories: 277 <br/> Carbs: 75 grams <br/> Fiber: 7 grams <br/> Protein: 2 grams <br/> Potassium: 20% of the RDI <br/>  Magnesium: 14% of the RDI <br/>  Copper: 18% of the RDI <br/> Manganese: 15% of the RDI <br/>  Iron: 5% of the RDI <br/> Vitamin B6: 12% of the RDI <br/> Dates are also high in antioxidants, which may contribute to many of their health benefits.  ",
                "benefits": "• Fruit_Benefits",
                "media": "102zVpPKQabbzzhtHux6n7n34rCHgP-Hc",
            },
            "2": {
                "name": "Orange",
                "description": "•  Generally an orange should have smoothly textured skin and be firm and heavy for its size. These will have higher juice content than those that are either spongy or lighter in weight.",
                "nutrition": "• Oranges, like other citrus fruits, are an excellent source of vitamin-C.Orange fruit contains a variety of phytochemicals.Oranges also contain very good levels of vitamin-A, and other flavonoid antioxidants such as a and ß -carotenes, ß -cryptoxanthin, zeaxanthin and lutein. These compounds have been known to have antioxidant properties.",
                "benefits": "• Antioxidants in oranges help protect skin from free radical damage known to cause signs of aging.<br/> • Drinking orange juice regularly prevents kidney diseases and reduce the risk of kidney stones.<br/> • Since they’re full of soluble fiber, oranges are helpful in lowering cholesterol.<br/> • Oranges are rich in citrus limonoids, proven to help fight a number of varieties of cancer including that of the lung, breast, stomach and colon.",
                "media": "139s4Z00FNPdvO5HzkUAHWPsECJrXDqsC",
            },
            "3": {
                "name": "Custard Apple",
                "description": "• The fruit is soft and chewy with a hard exterior. The flesh is white in color and has a creamy texture. Custard apple with its high calories and natural sugars are great as a dessert and as a nutritious snack. ",
                "nutrition": "•  Custard apples are rich in anti-oxidants like vitamin C. It is also rich in calcium, magnesium, iron, niacin & potassium. ",
                "benefits": "• Custard apple is great for healthy skin, healthy hair and better eyesight. It plays a role in moisturisation and anti-aging. <br/> • Custard apples are good for those who need to gain weight. A mixture of honey and custard apple when consumed regularly will help add on the required weight and those much required calories. <br/> • Custard apple helps develop the brain, nervous system and immune system of a fetus effectively. Regular consumption of custard apple also reduces the risk of miscarriage during pregnancy and minimizes the extent of labor pain during childbirth. ",
                "media": "12L0QxlSSrsoyE1KvLvDj9IVDI3AUonh1",
            },
        },
        "December": {
            "totalNumbers": "3",
            "1": {
                "name": "Strawberries",
                "description": "•  A beautiful and delicious small red fruit. Strawberries are available fresh,freeze-dried, and in jellies, syrups, and jams",
                "nutrition": "• It is packed with vitamins C, fiber, and particularly high levels of antioxidants known as polyphenols, strawberries are a sodium-free, fat-free, cholesterol-free, low-calorie food.",
                "benefits": "• The powerful antioxidants in strawberries may work against free radicals, inhibiting tumor growth and decreasing inflammation in the body. <br/> • Strawberries are a low glycemic index food and high in fiber, which helps to regulate blood sugar and keep it stable by avoiding extreme highs and lows.<br/> • It protects from various eye problems, prevent Heart diseases & cancer risk. It is one of the best fruit for immunity booster.",
                "media": "1Qkq6lhE7Z_ZTjVfdhHtN-EPdyiIOHkLe",
            },
            "2": {
                "name": "Pineapple",
                "description": "• The pineapple is a tropical plant with an edible multiple fruit consisting of coalesced berries, also called pineapples.",
                "nutrition": "•  Pineapples contain high amounts of vitamin C.  and manganese.Pineapples are tropical fruit that are rich in vitamins, enzymes and antioxidants.",
                "benefits": "• Pineapple mostly recommends to injured patients because its supports injuries healing process. <br/> • It is beneficial for preventing cancer risk, keeps your blood pressure in control. <br/> • In addition to having lots of vitamin C, pineapple’s bromelain may help reduce mucus in the throat and nose, i.e helpful on Coughs and Colds.<br/> • Pineapples can help reduce the risk of macular degeneration, a disease that affects the eyes as people age, due in part to its high amount of vitamin C and the antioxidants it contains.<br/> • Adding more pineapple to your diet will give you more of the antioxidants you need to slow the development of this sight-robbing condition.<br/>",
                "media": "1t8vIHjQK0fjqZgtWM55LSivc5-UCMJtp",
            },
            "3": {
                "name": "Sweet Lime (Mosambi)",
                "description": "• Mosambi (sweet lime) is a citrus fruit.It is green in color, oval in shape and ripens to yellow while having green pulp. ",
                "nutrition": "•If you are looking for a low fat or low calorie diet, then Mosambi is an ideal choice. One serving of Mosambi comprises of just 0.3gm of fat and 43 calories. <br/> • The sweet lime or Mosambi provides 0.8gm protein and 9.3mg carbs. Belonging to the family of citrus fruits, Mosambi is rich in vitamin C whereby one serving comprises of 50mg of vitamin C. <br/>  • It also contributes towards your daily potassium needs as one serving of Mosambi constitutes 490 mg of potassium. It also constitutes of iron, calcium, copper and phosphorus in some quantity. ",
                "benefits": "• The acidic content of mosambi helps to flush out body toxins and waste matter. Being rich in dietary fiber, mosambi acts as a purgative treatment for the ones who suffer from constipation. <br/> • Sweet lime juice prevents dehydration and is far better than carbonated drink which only gives acidity and burps. It is far better to drink mosambi juice when feeling dehydrated and thirsty. <br/> • It is high in vitamin C content which boosts immunity. It keeps one away from cold and flu. Regular consumption of Mosambi juice can improve the functioning of heart. ",
                "media": "1efW_zePbL4HjOjbUD2sz9CIbBG-7OYAz",
            },
        }
    }
    return (FruitContent);
}
